from turtle import *
from helpers import restore_state_when_finished, fly
def apple(size):
    pensize(10)
    color("black")
    begin_fill()
    x = 5
    with restore_state_when_finished():
        forward(size/5)
        right(10)
        forward(size/5)
        right(5)
        forward(size/5)
        right(15)
        for i in range(2):
            forward(size/10)
            right(15)
        forward(size/10)
        right(30)
        forward(size/10)
        right(5)
        for i in range(3):
            forward(size/(10/3))
            right(x)
            x = x + 5
        forward(size/10)
        right(45)
        forward(size/5)
        right(5)
        forward(size/5)
        right(5)
        for i in range(2):
            forward(size/10)
            right(10)
        forward(size/10)
        left(10)
        forward(size/10)
        right(5)
        forward(size/5)
        right(45)
        forward(size/10)
        right(15)
        forward(size/(10/3))
        right(10)
        for i in range(2):
            forward(size/(10/3))
            right(5)
        forward(size/10)
        right(30)
        for i in range(3):
        forward(size/10)
        right(15)
        forward(size/5)
        right(11)
        forward(size/(50/9))
        left(85)
        forward(size/15)
        color("red")
        end_fill()
        color("brown")
        forward(size/(5/2))
        color("red")
        end_fill()
        left(5)
        "Draws an apple that is filled with color"

def knife(size):
    pensize("5")
    color("black")
    begin_fill()
    with restore_state_when_finished():
                forward(size/(25/8))
                left(90)
                forward(size/(5/4))
                left(90)
                forward(size/(25/8))
                left(90)
                forward(size/(5/4))
                color("forestgreen")
                end_fill()
                color("black")
                "This part of the code function and fills the grip of the dagger to green and changes the color back to black for the outline."
                right(180)
                forward(size/(5/4))
                begin_fill()
                left(90)
                forward(size/(5/3))
                right(170)
                forward(size/(5/3))
                right(10)
                forward(size/(25/8))
                right(10)
                forward(size/(5/3))
                right(170)
                forward(size/(5/3))
                end_fill()
                "This part of the function draws and fills the guard of the dagger."
                right(180)
                forward(size/(5/3))
                left(170)
                forward(size/(5/3))
                right(75)
                begin_fill()
                forward(size*2)
                left(170.75)
                forward(size*2)
                color("silver")
                end_fill()
                "This part of the function draws and fills the blade of the dagger."

def knife_in_apple(v, m, size):
    fly(v, 108)
    setheading(90)
    knife(size/2)
    "Moves turtle to a coordinate before drawing the knife in the correct direction."
    setheading(130)
    fly(m, 108)
    apple(size)
    "Moves turtle to a coordinate before drawing the apple in the correct direction. The apple overlaps the knife and draws it over the knife, creating the illusion that the knife is in the apple."
